/*
    SE AGREGO JUGADOR  PARA PENSAR EN ESTE CONTEXTO DE ALGUNAS ACCIONES QUE PUEDE HABER Y NOS FACILITARÁ
    PARA REDUCIR ACCIONES DE OTRAS CLASES. A EVALUAR EN CLASE JUNTOS.
*/
export class Jugador {

}